# Generated by Django 3.0.5 on 2020-05-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0002_auto_20200503_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagereal',
            name='img',
            field=models.ImageField(default='', max_length=512, upload_to='C:\\Users\\sophrieet\\WeChatProjects\\miniprogram-1\\images'),
        ),
    ]
