# Generated by Django 3.0.5 on 2020-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0007_auto_20200504_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarimg',
            field=models.ImageField(default='', max_length=512, upload_to='images'),
        ),
    ]
