# Generated by Django 3.0.5 on 2020-05-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0008_user_avatarimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(default='请填写年龄', max_length=64, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_date',
            field=models.DateField(default='请填写初诊时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='请填写性别', max_length=64, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='请填写手机号', max_length=32, verbose_name='小程序授权手机号'),
        ),
    ]
