# Generated by Django 3.0.5 on 2020-05-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0009_auto_20200504_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_date',
            field=models.DateField(default='2020-05-04'),
        ),
    ]
