# Generated by Django 2.2.10 on 2020-05-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0010_auto_20200504_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userfix',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '患者提交信息', 'verbose_name_plural': '患者提交信息'},
        ),
        migrations.AlterModelOptions(
            name='imagereal',
            options={'verbose_name': '患者上传图像', 'verbose_name_plural': '患者上传图像'},
        ),
        migrations.AlterModelOptions(
            name='userfix',
            options={'verbose_name': '患者信息', 'verbose_name_plural': '患者信息'},
        ),
        migrations.AlterField(
            model_name='imagereal',
            name='img',
            field=models.ImageField(default='', max_length=512, upload_to='images', verbose_name='伤口图像'),
        ),
    ]
