# Generated by Django 2.2.10 on 2020-05-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0011_auto_20200507_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userfix',
            new_name='user',
        ),
    ]
