# Generated by Django 2.2.10 on 2020-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patapp', '0014_user_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': '医生信息', 'verbose_name_plural': '医生信息'},
        ),
        migrations.AddField(
            model_name='imagereal',
            name='imglocal',
            field=models.ImageField(default='', max_length=512, upload_to='images', verbose_name='伤口图像'),
        ),
    ]
